### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by rahulkapoor90** [saurabhmathur96/clickbait-detector#5]
Is there any possible way that this could be used as a chrome extension letting us know before the article?

**Comment by saurabhmathur96** [comment]
The deep learning model can be put on a server and the extension can call it via AJAX. @nh-99 is building something similar for facebook feeds

**Comment by rahulkapoor90** [comment]
Cool! Can you put it on a server and i'll make the extension for the online news publications/youtube and make an ajax request?

**Comment by rahulkapoor90** [comment]
how do i contribute to @nh-99 one? Private repo or something?

**Comment by saurabhmathur96** [comment]
App server is up and running at 

Usage example
```
GET http://clickbait-detector.herokuapp.com/detect?headline=15%20Beautifully%20Created%20Doors%20You%20Need%20To%20See%20Before%20You%20Die.%20The%20One%20In%20Soho%20Blew%20Me%20Away
```

Response
```

{
  "clickbaitiness": 93.5
}

```
